# config.py
# Camera calibration lives here (set once, never touched by the UI).
# Everything else is loaded from settings.json so the UI can persist changes.

import json
import numpy as np
from pathlib import Path

# ---------------------------------------------------------------------------
# Camera calibration — generated by camera_calibration.py
# Replace these arrays with your actual calibration output.
# ---------------------------------------------------------------------------

CAMERA_MATRIX = np.array([
    [2757.3684438599776, 0.0,                1156.2323363492503],
    [0.0,                2773.1375227967383,  775.4384227198979],
    [0.0,                0.0,                   1.0            ],
], dtype=np.float64)

DISTORTION_COEFFICIENTS = np.array(
    [0.019202280771496893, 0.6745707789527429, 0.014252213359000484,
     0.0015007128671278341, -3.565156939628043], dtype=np.float64
)

# Capture resolution — hardware-specific, not exposed in the UI.
IMAGE_RESOLUTION = (2304, 1296)

# ---------------------------------------------------------------------------
# Tunable settings — persisted in settings.json
# ---------------------------------------------------------------------------

_SETTINGS_PATH = Path(__file__).parent / "settings.json"

_DEFAULTS = {
    "lens_position":       8.0,
    "crop_bounds":         [50, 50, 2200, 1196],
    "aruco_dict_name":     "DICT_4X4_50",
    "aruco_marker_id":     0,
    "aruco_marker_size_mm": 50.0,
    "threshold_value":     127,
    "contour_min_area":    5000,
    "svg_output_path":     "output",
    "session_path":        "session",
}


def load_settings() -> dict:
    """Return settings from settings.json, falling back to defaults."""
    if _SETTINGS_PATH.exists():
        with open(_SETTINGS_PATH) as f:
            saved = json.load(f)
        return {**_DEFAULTS, **saved}
    return dict(_DEFAULTS)


def save_settings(settings: dict) -> None:
    """Write settings dict to settings.json."""
    with open(_SETTINGS_PATH, "w") as f:
        json.dump(settings, f, indent=2)


# Expose as module-level constants so all pipeline modules work unchanged.
_s = load_settings()

LENS_POSITION        = _s["lens_position"]
CROP_BOUNDS          = tuple(_s["crop_bounds"])
ARUCO_DICT_NAME      = _s["aruco_dict_name"]
ARUCO_MARKER_ID      = _s["aruco_marker_id"]
ARUCO_MARKER_SIZE_MM = _s["aruco_marker_size_mm"]
THRESHOLD_VALUE      = _s["threshold_value"]
CONTOUR_MIN_AREA     = _s["contour_min_area"]
SVG_OUTPUT_PATH      = _s["svg_output_path"]
SESSION_PATH         = _s["session_path"]
